<?php

$Document = $surface->Get('App.Document');
$PDF = $Document->GetArchivePath();

?>

<div class="Contain Promo AmericaFuckYeah"><div>
	<h2 class="MarginLineNone"><?php echo htmlentities($Document->GetTitle()) ?></h2>
	<h3 class="MarginLineNormal">
		Signed by <a href="#" style="FontWeightBold"><?php echo htmlentities($Document->GetSignedName()) ?></a>
		on <a href="#" style="FontWeightBold"><?php echo htmlentities($Document->GetDateSigned()) ?></a>
	</h3>
	<table class="WidthFull">
		<thead>
			<tr>
				<th class="TextAlignCenter TextWeightBold">Document Type</th>
				<th class="TextAlignCenter TextWeightBold">Date Signed</th>
				<th class="TextAlignCenter TextWeightBold">Date Published</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="TextAlignCenter"><?php echo htmlentities($Document->GetDocumentType()) ?></td>
				<td class="TextAlignCenter"><?php echo htmlentities($Document->GetDateSigned()) ?></td>
				<td class="TextAlignCenter"><?php echo htmlentities($Document->GetDatePublished()) ?></td>
			</tr>
		</tbody>
	</table>
</div></div>

<div class="Contain">
	<div>
	<legend>Source Documents</legend>
	<hr />
	<ul>
<?php foreach($Document->GetURLS() as $Label => $URL): ?>
		<li><a href="<?php echo $URL ?>" target="_blank"><?php echo $Label ?> (<?php echo App\Site\Filters::DomainFromURL($URL) ?>)</a></li>
<?php endforeach; ?>
	</ul>

	</div>
	<div>

<?php if($PDF): ?>
	<legend>Archived Document</legend>
	<hr />
	<p>Below is the PDF of this document which has been archived locally on
	this server.</p>
	<object class="ViewPDF" data="/pdf/<?php echo $Document->GetDocumentKey() ?>"></object>
<?php endif; ?>

</div></div>
