<?php

$TermSummary = $surface->Get('Home.TermSummary');
$PresidentSummary = $surface->Get('Home.PresidentSummary');
$LineLabelData = [
	'J','F','M','A','M','J','J','A','S','O','N','D',
	'J','F','M','A','M','J','J','A','S','O','N','D',
	'J','F','M','A','M','J','J','A','S','O','N','D',
	'J','F','M','A','M','J','J','A','S','O','N','D',
	'J'
];
$LineSeriesData = [];
$PieSeriesData = [];
$PieSeriesSum = 0;

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

// prepare a dataset that chartist can understand.

foreach(App\Term::$List as $Label => $TermInfo) {
	$LineSeriesData[] = [
		'value'     => array_values($TermSummary[$Label]),
		'className' => "ct-series dataset-{$TermInfo['SignedBy']}-{$TermInfo['Term']}",
		'meta'      => $Label
	];
}

foreach($PresidentSummary as $Label => $Value) {
	$PieSeriesData[] = [
		'value'     => (Int)$Value,
		'name'      => 'name',
		'className' => "ct-series dataset-{$Label}-1",
		'meta'      => 'meta'
	];

	$PieSeriesSum += (Int)$Value;
}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

?>

<div class="Contain Promo AmericaFuckYeah"><div style="">
	<legend class="TextAlignCenter">Documents Per Month Per Term</legend><hr />
	<div class="ChartTermOverTime MarginLineNormal" style="height:300px;background:rgba(0,0,0,0.5);"></div>
	<div>
		<div class="FloatLeft WidthHalf WidthPadded">
			<legend class="TextAlignCenter">Legend</legend><hr />
			<div class="ChartTermOverTimeLegend" style="height:300px;background:rgba(0,0,0,0.5);">
				<ul>
<?php foreach(App\Term::$List as $Label => $TermInfo): ?>
					<li class="FloatLeft WidthHalf WidthPadded dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?>"><a app-dataset="dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?>" href="#" onclick="return false;"><?php echo $Label ?></a></li>
<?php endforeach; ?>
				</ul>
			</div>
		</div>
		<div class="FloatRight WidthHalf WidthPadded">
			<legend class="TextAlignCenter">Total Document Share</legend><hr />
			<div class="ChartTermSummary" style="height:300px;background:rgba(0,0,0,0.5);"></div>
		</div>
		<hr class="FloatClear" />
	</div>


</div></div>

<style type="text/css">
.ct-chart-line .ct-point:hover { stroke: #fff; stroke-width: 16; }
.ct-chart-line .ct-label { color: #fff; }
.ct-chart-pie .ct-label { color: #000; text-shadow: 0px 0px 3px #000; }
.ct-grid { stroke: #666; }
</style>

<script type="text/javascript">
jQuery(document)
.ready(function(){

	var Chart = jQuery('.ChartTermOverTime');

	jQuery('.ChartTermOverTimeLegend li a')
	.on('mouseover',function(){
		// preview a series when hovering.

		var Dataset = jQuery(this).attr('app-dataset');

		jQuery('.ChartTermOverTime .ct-series:not(.' + Dataset + ')')
		.addClass('ChartDefocusTemp');

		return;
	})
	.on('mouseout',function(){
		// clear preview when mousing out.

		jQuery('.ChartTermOverTime .ct-series')
		.removeClass('ChartDefocusTemp');

		return;
	})
	.on('click',function(){
		// lock a series for preview when clicked.

		var Dataset = jQuery(this).attr('app-dataset');
		var Series = Chart.find('.ct-series.' + Dataset);

		jQuery(this)
		.toggleClass('ChartFocus');

		Series
		.toggleClass('ChartFocus');

		Chart
		.find('.ct-series')
		.removeClass('ChartDefocus');

		if(Chart.find('.ct-series.ChartFocus').length > 0) {
			Chart
			.find('.ct-series:not(.ChartFocus)')
			.addClass('ChartDefocus');
		}

		return;
	});

	return;
});

function RenderLineChart() {
	var Dataset = {
		labels: <?php echo json_encode($LineLabelData) ?>,
		series: <?php echo json_encode($LineSeriesData) ?>
	};

	var Options = {
		plugins: [
			Chartist.plugins.tooltip({
				'anchorToPoint': false,
				'appendToBody': true
			})
		],
		showArea: false,
		showLine: true,
		showPoint: true,
		fullWidth: true,
		axisY: {
			onlyInteger: true,
		},
		axisX: {
			showLabel: true,
			showGrid: false
		},
		chartPadding: {
			top: 16,
			right: 16,
			bottom: 0,
			left: 0
		}
	};

	var MoreOptions = {

	};

	new Chartist.Line(
		'.ChartTermOverTime',
		Dataset,
		Options,
		MoreOptions
	);
}

function RenderPieChart() {

	var Dataset = {

		series: <?php echo json_encode($PieSeriesData) ?>,
		sum: <?php echo json_encode($PieSeriesSum) ?>
	};

	var Options = {
		labelInterpolationFnc: function(value) {
			return value + ' (' + Math.round(value / Dataset.sum * 100) + '%)';
		},
		labelOffset: 50,
		labelPosition: 'inside',
		labelDirection: 'implode',
		donut: false,
		donutWidth: 64,
		chartPadding: 16
	};

	new Chartist.Pie(
		'.ChartTermSummary',
		Dataset,
		Options
	);
}

RenderLineChart();
RenderPieChart();
</script>
