<?php

$TermSummary = $surface->Get('Home.TermSummary');
$LineSeriesData = [];

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

// prepare a dataset that chartist can understand.

foreach(App\Term::$List as $Label => $TermInfo) {
	$LineSeriesData[] = [
		'value' => array_values($TermSummary[$Label]),
		'className' => "ct-series dataset-{$TermInfo['SignedBy']}-{$TermInfo['Term']}"
	];
}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

?>

<div class="Contain Promo AmericaFuckYeah"><div style="">
	<div class="ChartTermOverTime" style="width:100%;height:300px;"></div>
	<div class="ChartTermOverTimeLegend">
		<ul>
<?php foreach(App\Term::$List as $Label => $TermInfo): ?>
			<li class="dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?>"><a href=""><?php echo $Label ?></a></li>
<?php endforeach; ?>
		</ul>
	</div>
</div></div>

<style type="text/css">
.ct-label { color: #fff; text-align: left !important; text-anchor: start !important; }
.ct-grid { stroke: #666; }
</style>

<script type="text/javascript">
var Dataset = {
	labels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
	series: <?php echo json_encode($LineSeriesData) ?>
};

var Options = {
	showArea: false,
	showLine: true,
	showPoint: true,
	fullWidth: true,
	axisY: {
		onlyInteger: true,
	},
	axisX: {
		showLabel: true,
		showGrid: false
	}
};

new Chartist.Line(
	'.ChartTermOverTime',
	Dataset,
	Options
);
</script>
