<!DOCTYPE html>
<html>
<head>
	<title><?php $surface->Show('page-title') ?></title>

	<!-- scripting -->
	<script type="text/javascript" src="/share/other/dist/scripts.js"></script>

	<!-- styling -->
	<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&amp;subset=latin-ext" />
	<link type="text/css" rel="stylesheet" href="/share/other/dist/styles.css" />
	<link type="text/css" rel="stylesheet" href="/themes/default/design.css" />

	<style type="text/css">
<?php foreach(App\Term::$List as $Label => $TermInfo): ?>
		g.dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?> {
			stroke: <?php echo $TermInfo['LineColour'] ?>;
		}
		li.dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?>,
		li.dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?> a {
			color: <?php echo $TermInfo['LineColour'] ?>;
			border-color: <?php echo $TermInfo['LineColour'] ?>;
		}
<?php endforeach; ?>
	</style>

</head>
<body>

<header>
	<div class="Contain"><div>
		<div class="TextAlignCenter">
			<h1><a href="/"><i class="TextColourRed fa fa-bank"></i> Presidential Order Archive</h1></a>
		</div>
	</div></div>
	<div class="Contain"><div>
		<nav>
			<ul>
				<li><a href="/about/">About The Data</a></li>
				<li><a href="/api/">API</a></li>
			</ul>
		</nav>
	</div>
</header>

<div id="Main">

<?php echo $surface->Get('stdout') ?>

</div>

</body>
</html>