<!DOCTYPE html>
<html>
<head>
	<title><?php $surface->Show('page-title') ?></title>
	<link rel="icon" href="/favicon.png" type="image/png">
	<link rel="shortcut icon" href="/favicon.png" type="image/png">

	<!-- scripting -->
	<script type="text/javascript" src="/share/other/dist/scripts.js"></script>

	<!-- styling -->
	<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&amp;subset=latin-ext" />
	<link type="text/css" rel="stylesheet" href="/share/other/dist/styles.css" />
	<link type="text/css" rel="stylesheet" href="/themes/default/design.css" />

	<style type="text/css">
<?php foreach(App\Term::$List as $Label => $TermInfo): ?>
		.ct-chart-line .dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?> {
			stroke: <?php echo $TermInfo['LineColour'] ?>;
		}
		.ct-chart-pie .dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?>,
		.ct-chart-donut .dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?> {
			fill: <?php echo $TermInfo['LineColour'] ?>;
			stroke: <?php echo $TermInfo['LineColour'] ?>;
		}
		li.dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?>,
		li.dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?> a {
			color: <?php echo $TermInfo['LineColour'] ?>;
			border-color: <?php echo $TermInfo['LineColour'] ?>;
		}
		li.dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?>.ChartFocus,
		li.dataset-<?php echo "{$TermInfo['SignedBy']}-{$TermInfo['Term']}" ?> a.ChartFocus {
			background: <?php echo $TermInfo['LineColour'] ?>;
			color: #000;
		}
<?php endforeach; ?>
	</style>

</head>
<body>

<header>
	<div class="Contain"><div>
		<div class="FloatLeft">
			<h1><a href="/"><i class="TextColourRed fa fa-bank"></i> PDA</h1></a>
			<p>Presidential Document Archive</p>
		</div>
		<div class="FloatRight TextWeightBold">
			<span class="TextColourRed TextWeightBold">Last Fetch:</span> <?php echo App\Site\Util::GetFetchDate() ?>
		</div>
		<hr class="FloatClear" />
	</div></div>
	<div class="Contain"><div>
		<nav>
			<ul>
				<li><a href="/about/">About The Data</a></li>
				<li><a href="/api/">API</a></li>
				<li><a href="https://github.com/bobmagicii/presidential-document-archive" target="_blank">GitHub</a></li>
			</ul>
		</nav>
	</div>
</header>

<div id="Main">

<?php echo $surface->Get('stdout') ?>

</div>

</body>
</html>